#--------------------------------------------------
# Top-level Makefile for GalaxyFinder
# Generated by ./configure
#--------------------------------------------------

SUBDIRS = GalCenter NewGalFinder NewDD

.PHONY: all galcenter galfinder newdd clean new

all: galcenter galfinder newdd

galcenter:
	$(MAKE) -C GalCenter all

galfinder:
	$(MAKE) -C NewGalFinder all

newdd:
	$(MAKE) -C NewDD all

newdd-lib:
	$(MAKE) -C NewDD default

clean:
	$(MAKE) -C GalCenter clean
	$(MAKE) -C NewGalFinder clean
	$(MAKE) -C NewDD clean

new:
	$(MAKE) -C GalCenter new
	$(MAKE) -C NewGalFinder new
	$(MAKE) -C NewDD new
