#pragma once
void link_galaxy_members(SimpleBasicParticleType *particles, int n_particles, int n_cores, Coretype *cores);
int compare_float_ascending(const void *a,const void *b);
void unwrap_periodic_box(SimpleBasicParticleType *particles,lint n_particles,float *xinit,float *yinit, float *zinit,float *xmax,float *ymax,float *zmax);
int compare_cores_by_peak_density(const void *a, const void *b);
int compare_cores_by_star_count(const void *a, const void *b);
int merge_nearby_peaks(SimpleBasicParticleType *particles,int n_particles,Coretype *cores,int n_cores, int iflag, float fof_link);
int find_sph_density_peaks(float *den,int numneigh,long long *neighbor,int n_particles, Coretype **Core, int jflag, SimpleBasicParticleType *particles);
void copy_density_into_particle_state(float *density,int n_particles,Coretype *cores,int n_cores);
int count_members_in_radius(SimpleBasicParticleType *particles,int n_particles,int *indexes, float cx,float cy,float cz,float radius2);
int shell_particles_from_remaining(SimpleBasicParticleType *particles,int n_particles,int shell_id, int *indexes, Coretype *one_core);
int member_indexes_in_shell(int n_particles,int galaxy_id, int *indexes,int shell_id);
int shell_candidates_from_pool(SimpleBasicParticleType *particles, int shell_id, int *indexes, Coretype *one_core, int *remaining_pool, int nremaining);
int member_indexes_from_csr(int galaxy_id, int *indexes, int shell_id, int *halo_csr_list, int *halo_csr_offset);
int next_unenclosed_core(Coretype *cores, int n_cores,float threshold);
void put_unassigned_in_last_shell(int n_particles,Coretype *cores,int n_cores);
void build_density_shell(int n_particles,long long *neighbor,int n_neighbors, Coretype *cores,int n_cores, float dthreshold);
int compare_cores_by_density(const void *a,const void *b);
int merge_underpopulated_dark_cores(SimpleBasicParticleType *particles,int n_particles,Coretype *cores,int n_cores, long long *neighbor,int n_neighbors);
int merge_underpopulated_cores(SimpleBasicParticleType *particles,int n_particles,Coretype *cores,int n_cores, long long *neighbor,int n_neighbors);
double nfw_concentration(double mass);
double nfw_alpha(double c,double s);
double circular_velocity_squared(double mass, double Rv);
double nfw_shape_factor(double c);
double virial_radius(double Mvir);
double background_potential(double Mvir);
double tidal_radius_factor(int n_particles, int myid, int mp, int uid, int mpall, Coretype *cores, float Mvir, double mratio, double bmass);
int trim_cores_to_saddle(SimpleBasicParticleType *particles,int n_particles,long long *neighbor, int n_neighbors,Coretype *cores,int n_cores);
void self_halo_potential(int n_particles,Vector3d *r,float *mass,float *penergy);
void external_halo_potential(int nend,Vector3d *r,float *mass, float *penergy, int snp, Vector3d *sr, float *smass);
int count_bound_against_members(SampledParticle *candidate_samples,int tnp,unsigned char *bndflag, SampledParticle *member_samples,int snp, Coretype *one_core);
int claim_shell_particles(SampledParticle *candidate_samples,int tnp, SampledParticle *member_samples, int snp, SimpleBasicParticleType *particles,int n_particles,Coretype *one_core);
int count_self_bound(SampledParticle *samples,int n_particles,unsigned char *bndflag, Coretype *one_core, int satellite_frame);
int unbind_isolated_halo(SampledParticle *samples,int n_particles,SimpleBasicParticleType *particles,int galaxy_id);
int unbind_one_galaxy(int nkp,SampledParticle *samples,int n_particles,SimpleBasicParticleType *particles,int galaxy_id, Coretype *cores, int satellite_frame);
int central_stellar_core(Coretype *cores, int n_cores);
int buried_in_heavier_core(Coretype *cores, Coresorttype *order, int n_order, int self_index);
int list_own_members(int n_particles, int galaxy_id, int *list);
int compare_cores_by_mass(const void *a,const void *b);
void init_nfw_tidal_table();
void set_tidal_radii(Coretype *cores,int n_cores, Coresorttype *core_order,int ncore,SimpleBasicParticleType *particles,int n_particles);
int indexes_of_galaxy(int n_particles,int galaxy_id, int *indexes);
void return_unbound_shell_particles(int shell_id,SimpleBasicParticleType *particles);
void pack_samples_parallel(SampledParticle *samples, int *list, int nlist,SimpleBasicParticleType *particles);
int fof_find_root(ompFoFParticleType *ptl,int i);
int fof_within_link(ompFoFParticleType *ptl, int i,int j);
void fof_unite(ompFoFParticleType *ptl, int i,int j);
void link_members_openmp(SimpleBasicParticleType *particles, int n_particles, int n_cores, Coretype *cores, int ptype);
void link_members_stars(SimpleBasicParticleType *particles,int n_particles, int n_cores, Coretype *cores);
void link_members_all_species(SimpleBasicParticleType *particles,int n_particles, int n_cores, Coretype *cores);
int list_tidal_candidates_adaptive(SimpleBasicParticleType *particles,int n_particles,int hid,int *list, Coretype *cores, Coresorttype *core_order,int now,int n_cores);
int list_tidal_candidates(SimpleBasicParticleType *particles,int n_particles,int hid,int *list, Coretype *cores, Coresorttype *core_order,int now,int n_cores);
double copy_raw_particles(FoFTPtlStruct *raw,SimpleBasicParticleType *particles,lint n_particles);
float total_star_mass(SimpleBasicParticleType *particles, int n_particles);
int count_stars(SimpleBasicParticleType *particles, int n_particles);
float total_dm_mass(SimpleBasicParticleType *particles, int n_particles);
int _dump_stage_enabled(const char *tag);
void write_stage_snapshot(FoFTPtlStruct *raw, lint n_particles, int n_cores, Coretype *cores, const char *tag);
int _pp_cmp_ascpeak(const void *a, const void *b);
int _pp_find(int *p, int x);
int prune_shallow_peaks(int n_particles, Coretype *cores, int n_cores, SimpleBasicParticleType *particles, float tau);
int find_galaxies(FoFTPtlStruct *raw, lint n_particles,lint *galaxy_ids);
int assign_members_from_watershed(SimpleBasicParticleType *particles, int n_particles, long long *neighbor, int n_neighbors, Coretype *cores, int n_cores);
